add check for php5-mysql when mysql is selected

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -59,6 +59,11 @@ for \$s (@statements) { \$db->do(\$s) || die 'Failed to execute SQL: ' . \$s . '
     return $ret
 }
 
+check_php5myinstalled() {
+    dpkg -s php5-mysql || return 1
+    return 0
+}
+
 check_myinstalled() {
     test -x /usr/sbin/mysqld || return 1
     type mysql >/dev/null 2>&1 || return 1
@@ -354,6 +359,13 @@ case "$1" in
 			if test -d $unud; then
 			    cp -f "/usr/share/moodle/update-notifier/$mrr_mysql_server" "$unud/$mrr_mysql_server"
 			fi
+			exit 0
+		    fi
+
+		    if ! check_php5myinstalled; then
+			echo 'Error - You have specified that you wish to use a mysql' >&2
+			echo 'database, but php5-mysql is not installed. You must install' >&2
+			echo 'php5-mysql before you can complete your moodle installation.' >&2
 			exit 0
 		    fi
 
