* renamed prerm script * significantly rewrote postinst and other maintainer scripts to improve user experience and package maintainability
modified:   debian/changelog
modified:   debian/config
modified:   debian/dirs
modified:   debian/install
modified:   debian/postinst
modified:   debian/postrm
modified:   debian/rules
modified:   debian/templates

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -21,6 +21,11 @@
 #     installation fails and the `postinst' is called with `abort-upgrade',
 #     `abort-remove' or `abort-deconfigure'.
 
+unud=/var/lib/update-notifier/user.d
+mrr_mysql_server=moodle-reconfigure-required_mysql-server
+mrr_postgresql=moodle-reconfigure-required_postgresql
+mrr_fqdn_check=moodle-reconfigure-required_fqdn-check
+
 # escape_quotes borrowed originally from Ubuntu mythtv package
 escape_quotes() {
     cat <<EOF | sed -e "s/'/\\\\'/g"
@@ -30,20 +35,13 @@ EOF
 
 # DoSQL borrowed originally from Ubuntu mythtv package
 DoMySQL() {
-    local dbtype
-    dbtype="$1"
-    local host
-    host="$2"
-    local admin_username
-    admin_username="$3"
-    local admin_password
-    admin_password="$4"
-    local database
-    database="$5"
-    local statement
-    statement="`escape_quotes \"$6\"`"
-    local tmp
-    tmp=`tempfile -m 600`
+    local dbtype="$1"
+    local host="$2"
+    local admin_username="$3"
+    local admin_password="$4"
+    local database="$5"
+    local statement="`escape_quotes \"$6\"`"
+    local tmp=`tempfile -m 600`
 	cat <<EOF >$tmp
 $admin_password
 EOF
@@ -61,21 +59,33 @@ for \$s (@statements) { \$db->do(\$s) || die 'Failed to execute SQL: ' . \$s . '
     return $ret
 }
 
+check_myinstalled() {
+    test -x /usr/sbin/mysqld || return 1
+    type mysql >/dev/null 2>&1 || return 1
+    return 0
+}
+
+check_pginstalled() {
+    type pg_lsclusters >/dev/null 2>&1 || return 1
+    type psql >/dev/null 2>&1 || return 1
+    return 0
+}
+
 check_pgsafe() {
     dbname="$1"
 
-    [ -z "`type -p pg_lsclusters`" ] && { echo 'pg_lsclusters is not in my $PATH.'; return 1; }
+    type pg_lsclusters >/dev/null 2>&1 || { echo 'pg_lsclusters not found in $PATH'; return 1; }
     o=$(pg_lsclusters -h) || { echo "pg_lsclusters failed."; return 1; }
 
     if [ $(echo "$o" | wc -l) != 1 ]; then
-        echo "You have configured more than one PostgreSQL cluster."
+        echo "You have configured more than one PostgreSQL cluster." >&2
         return 1
     fi
 
     echo "$o" | if read VERSION CLUSTER trash; then
         cf="/etc/postgresql/$VERSION/$CLUSTER/pg_hba.conf"
         grep -q '^local.*all.*all.*ident.*sameuser$' "$cf" || {
-            echo "Your settings in $cf do not allow me to continue."
+            echo "Your settings in $cf do not allow me to continue." >&2
             return 1;
     }
     fi
@@ -88,35 +98,55 @@ check_pgsafe() {
     return 0
 }
 
-webserver="apache2"
-
 get_config() {
+
+    # Multiple webservers were presented in the past.
+    # Multiple webservers may be presented in the future.
+    webserver="apache2"
+
+    db_get moodle/local_only
+    local_only="$RET"
+
+    db_get moodle/fqdn_check
+    if [ "$RET" = "false" ]; then
+	db_set moodle/fqdn_check true
+	echo 'moodle configuration left incomplete pending verification of FQDN' >&2
+	if test -d $unud; then
+	    cp -f "/usr/share/moodle/update-notifier/$mrr_fqdn_check" "$unud/$mrr_fqdn_check"
+	fi
+	exit 0
+    fi
+
+    db_get moodle/https_only
+    https_only="$RET"
+
     db_get moodle/db_server
     db_server="$RET"
 
     db_get moodle/db_host
     db_host="$RET"
 
-    db_get moodle/db_postgres_create
-    db_pgcreate="$RET"
+    db_get moodle/db_create
+    db_create="$RET"
 
     case $db_server in
 	"postgresql")
 	    db_type="postgres7"
-	    db_port=5432 ;;
+	    db_port=5432
+	    dba_name=postgres
+	    ;;
 
 	"mysql-server")
 	    db_type="mysql"
-	    db_port=3306 ;;
+	    db_port=3306
+	    dba_name=root
+	    ;;
 	*)
 	    echo "Unknown database server type: $db_server"
 	    die
     esac
 
-    db_get moodle/dba_name
-    dba_name="$RET"
-
-    db_get moodle/dba_password
+    db_get moodle/dba_password || true
     dba_password="$RET"
 
     db_get moodle/dbu_name
@@ -128,7 +158,85 @@ get_config() {
     db_name='moodle'
 }
 
-handle_config() {
+apache_config() {
+
+    if [ "$local_only" = "true" ]; then
+	allowdeny="order deny,allow
+deny from all
+allow from 127.0.0.0/255.0.0.0"
+    else
+	allowdeny="order allow,deny
+allow from all"
+    fi
+
+    cfile=/etc/moodle/apache.conf
+    tempcfile=`tempfile`
+    cat > $tempcfile <<EOF
+# This file has been generated by debconf
+
+Alias /moodle /usr/share/moodle/
+
+<DirectoryMatch /usr/share/moodle/>
+
+Options +FollowSymLinks
+AllowOverride None
+
+${allowdeny}
+
+<IfModule mod_php5.c>
+	php_flag magic_quotes_gpc On
+	php_flag magic_quotes_runtime Off
+	php_flag file_uploads On
+	php_flag short_open_tag On
+	php_flag session.auto_start Off
+	php_flag session.bug_compat_warn Off
+
+	php_value upload_max_filesize 2M
+	php_value post_max_size 2M
+</IfModule>
+
+<IfModule mod_php4.c>
+	php_flag magic_quotes_gpc On
+	php_flag magic_quotes_runtime Off
+	php_flag file_uploads On
+	php_flag short_open_tag On
+	php_flag session.auto_start Off
+	php_flag session.bug_compat_warn Off
+
+	php_value upload_max_filesize 2M
+	php_value post_max_size 2M
+</IfModule>
+
+<IfModule mod_dir.c>
+	DirectoryIndex index.php
+</IfModule>
+
+</DirectoryMatch>
+EOF
+    ucf --debconf-ok $tempcfile $cfile
+    chmod 640 $cfile
+    chown www-data:www-data $cfile
+}
+
+moodle_config() {
+
+    if [ "$https_only" = "true" ]; then
+	protocol="https"
+    else
+	protocol="http"
+    fi
+
+    fqdn=`hostname --fqdn`
+    if [ -z "$fqdn" ]; then
+	echo 'moodle configuration left incomplete pending configuration of FQDN' >&2
+	if test -d $unud; then
+	    cp -f "/usr/share/moodle/update-notifier/$mrr_fqdn_check" "$unud/$mrr_fqdn_check"
+	fi
+	exit 0
+    fi
+
+    wwwroot="$protocol://$fqdn/moodle";
+
     cfile=/etc/moodle/config.php
     tempcfile=`tempfile`
     cat > $tempcfile <<EOF
@@ -181,11 +289,6 @@ EOF
     chown www-data:www-data $cfile
 }
 
-db_not_installed() {
-    echo "Please install the chosen Moodle SGBD: $db_server, then try"
-    echo "dpkg-reconfigure moodle"
-}
-
 case "$1" in
     configure)
 	. /usr/share/debconf/confmodule
@@ -196,6 +299,7 @@ case "$1" in
 	
 	# Read debconf and edit the config file accordingly
 	get_config
+	apache_config
 	handle_config
 	db_stop
 
@@ -230,45 +334,73 @@ case "$1" in
 
 	   fi
 	fi
-	invoke-rc.d ${webserver} reload || true
+	invoke-rc.d ${webserver} reload >/dev/null || true
 
 	# care about the database creation
-
 	case "$db_type" in
 	    mysql)
-		if ! DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "$db_name" "SELECT NULL" 2>/dev/null; then
+		if [ "$db_create" = "false" ]; then
+		    echo "Remember that you have elected to create your MySQL database manually." >&2
+		else
+		    if ! check_myinstalled; then
+			echo 'Error - You have specified that you wish to use a mysql' >&2
+			echo 'database, but either mysql-server or mysql-client is ' >&2
+			echo 'not installed. You must install mysql-server and mysql-client' >&2
+			echo 'and then reconfigure moodle.' >&2
+			if test -d $unud; then
+			    cp -f "/usr/share/moodle/update-notifier/$mrr_mysql_server" "$unud/$mrr_mysql_server"
+			fi
+			exit 0
+		    fi
+
+		    if ! DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "$db_name" "SELECT NULL" 2>/dev/null; then
 			if ! DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "" \
 			     "CREATE DATABASE $db_name"; then
-				echo "Failed to create database (incorrect admin username/password?)" >&2
-				echo "It's also possible that mysql-server wasn't running.  After install" >&2
-				echo "is completed, you will need to make sure mysql-server is running" >&2
-				echo "and that you supplied correct information. Try:" >&2
-				echo "sudo dpkg-reconfigure moodle" >&2
-				# silently exit, instead pop up a notification for user indicating this
-				unud=/var/lib/update-notifier/user.d
-				if test -d $uund; then
-				    cp -f /usr/share/moodle/moodle-reconfigure-required.update-notifier \
-				          /var/lib/update-notifier/user.d/moodle-reconfigure-required
-				fi
-				exit 0
+			    echo "Failed to create database (incorrect admin username/password?)" >&2
+			    echo "It's also possible that mysql-server wasn't running.  After install" >&2
+			    echo "is completed, you will need to make sure mysql-server is running" >&2
+			    echo "and that you supplied correct information. Try:" >&2
+			    echo "sudo dpkg-reconfigure moodle" >&2
+			    # silently exit, instead pop up a notification for user indicating this
+			    if test -d $unud; then
+				cp -f "/usr/share/moodle/update-notifier/$mrr_mysql_server" "$unud/$mrr_mysql_server"
+			    fi
+			    exit 0
 			fi
-		fi
-		DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "$db_name" \
-		    "GRANT ALL PRIVILEGES ON $db_name.* TO $dbu_name@localhost IDENTIFIED BY '$dbu_password'"
+		    fi
+		    DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "$db_name" \
+		            "GRANT ALL PRIVILEGES ON $db_name.* TO $dbu_name@localhost IDENTIFIED BY '$dbu_password'"
 
-		DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "$db_name" \
-		    "GRANT ALL PRIVILEGES ON $db_name.* TO $dbu_name@'%' IDENTIFIED BY '$dbu_password'"
+		    DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "$db_name" \
+		            "GRANT ALL PRIVILEGES ON $db_name.* TO $dbu_name@'%' IDENTIFIED BY '$dbu_password'"
+		fi
 	    ;;
 	    postgres7)
-	        if [ "$db_pgcreate" = "false" ] || ! check_pgsafe "$db_name"; then
-		    echo "You must create your PostgreSQL database manually."
+		if [ "$db_create" = "false" ]; then
+		    echo "Remember that you have elected to create your PostgreSQL database manually." >&2
 		else
-                    id "$dbu_name" 2> /dev/null || adduser --system --home /nonexistent --no-create-home --disabled-login "$dbu_name"
-		    su -c "psql --command \"CREATE ROLE $dbu_name PASSWORD '$dbu_password' NOSUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;\"" postgres
-		    su -c "createdb -E UTF8 -O \"$dbu_name\" \"$db_name\"" postgres
+		    if ! check_pginstalled; then
+			echo 'Error - You have specified that you wish to use a postgresql' >&2
+			echo 'database, but either postgresql or postgresql-client is not installed.' >&2
+			echo 'You must install postgresql and postgresql-client and then reconfigure moodle.' >&2
+			if test -d $unud; then
+			    cp -f "/usr/share/moodle/update-notifier/$mrr_postgresql" "$unud/$mrr_postgresql"
+			fi
+			exit 0
+		    fi
+
+		    if ! check_pgsafe "$db_name"; then
+			echo "Error - You must create your PostgreSQL database manually." >&2
+		    else
+			id "$dbu_name" 2>/dev/null || adduser --system --home /nonexistent --no-create-home --disabled-login "$dbu_name" >/dev/null
+			su -c "psql --command \"CREATE ROLE $dbu_name PASSWORD '$dbu_password' NOSUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;\"" $dba_name >/dev/null
+			su -c "createdb -E UTF8 -O \"$dbu_name\" \"$db_name\"" $dba_name >/dev/null
+		    fi
 		fi
 	    ;;
 	esac
+
+	echo "Moodle URL: $wwwroot"
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
