Merge debconf and database setup from Ubuntu

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -21,6 +21,66 @@
 #     installation fails and the `postinst' is called with `abort-upgrade',
 #     `abort-remove' or `abort-deconfigure'.
 
+# escape_quotes borrowed originally from Ubuntu mythtv package
+escape_quotes() {
+    cat <<EOF | sed -e "s/'/\\\\'/g"
+$1
+EOF
+}
+
+# DoSQL borrowed originally from Ubuntu mythtv package
+DoMySQL() {
+    local dbtype="$1"
+    local host="$2"
+    local admin_username="$3"
+    local admin_password="$4"
+    local database="$5"
+    local statement="`escape_quotes \"$6\"`"
+    local tmp=`tempfile -m 600`
+	cat <<EOF >$tmp
+$admin_password
+EOF
+    perl -e "
+use DBI;
+chomp(\$password=<>);
+@statements=split(/;/, '$statement');
+\$db = DBI->connect('dbi:mysql:host=$host;database=$database',
+		    '$admin_username', \$password,
+		    { PrintError => 0 }) || die 'Failed to connect to database: ' . \$DBI::errstr;
+for \$s (@statements) { \$db->do(\$s) || die 'Failed to execute SQL: ' . \$s . '\n' . \$DBI::errstr; }
+" < $tmp
+    ret=$?
+    rm -f $tmp
+    return $ret
+}
+
+check_pgsafe() {
+    dbname="$1"
+
+    [ -z "`type -p pg_lsclusters`" ] && { echo 'pg_lsclusters is not in my $PATH.'; return 1; }
+    o=$(pg_lsclusters -h) || { echo "pg_lsclusters failed."; return 1; }
+
+    if [ $(echo "$o" | wc -l) != 1 ]; then
+        echo "You have configured more than one PostgreSQL cluster."
+        return 1
+    fi
+
+    echo "$o" | if read VERSION CLUSTER trash; then
+        cf="/etc/postgresql/$VERSION/$CLUSTER/pg_hba.conf"
+        grep -q '^local.*all.*all.*ident.*sameuser$' "$cf" || {
+            echo "Your settings in $cf do not allow me to continue."
+            return 1;
+    }
+    fi
+
+    su -c 'psql -Atl' postgres | grep "^$dbname|" && {
+        echo "There is already a database named $dbname."
+        return 1;
+    }
+
+    return 0
+}
+
 get_config() {
     db_get moodle/webserver
     webserver="$RET"
@@ -31,6 +91,9 @@ get_config() {
     db_get moodle/db_host
     db_host="$RET"
 
+    db_get moodle/db_postgres_create
+    db_pgcreate="$RET"
+
     case $db_server in
 	"postgresql")
 	    db_type="postgres7"
@@ -39,6 +102,9 @@ get_config() {
 	"mysql-server")
 	    db_type="mysql"
 	    db_port=3306 ;;
+	*)
+	    echo "Unknown database server type: $db_server"
+	    die
     esac
 
     db_get moodle/dba_name
@@ -52,6 +118,8 @@ get_config() {
 
     db_get moodle/dbu_password
     dbu_password="$RET"
+
+    db_name='moodle'
 }
 
 handle_config() {
@@ -73,7 +141,7 @@ handle_config() {
 
  \$CFG->dbtype = '${db_type}';
  \$CFG->dbhost = '${db_host}';
- \$CFG->dbname = 'moodle';
+ \$CFG->dbname = '${db_name}';
  \$CFG->dbuser = '${dbu_name}';
  \$CFG->dbpass = '${dbu_password}';
  \$CFG->prefix = 'mdl_';
@@ -109,7 +177,7 @@ handle_config() {
 // RETURNS, OR ANYTHING ELSE AFTER THE TWO CHARACTERS ON THE NEXT LINE.
 ?>
 EOF
-    ucf $tempcfile $cfile
+    ucf --debconf-ok $tempcfile $cfile
     chmod 640 $cfile
     chown www-data:www-data $cfile
 }
@@ -129,9 +197,8 @@ case "$1" in
 	
 	# Read debconf and edit the config file accordingly
 	get_config
-	db_stop
-	exec 0<&1
 	handle_config
+	db_stop
 
 	if [ -r /etc/moodle/config.php ]; then
 	      [ -f $moodledir/config.php ] && rm $moodledir/config.php
@@ -165,63 +232,45 @@ case "$1" in
 
 	   fi
 	fi
-	server=${webserver}
-	servers="apache apache-ssl apache-perl apache2"
-	# if [ "$status" = "uncomment" -o "$status" = "include" ]; then
-	    restart=" ${server} ${restart}"
-	# fi
-	. /usr/share/wwwconfig-common/restart.sh || true
+	invoke-rc.d ${webserver} reload || true
 
 	# care about the database creation
 
-	dbname=moodle
-	dbserver=$db_host
-	dbadmin=$dba_name
-	dbadmpass=$dba_password
-	dbuser=$dbu_name
-	dbpass=$dbu_password
+	case "$db_type" in
+	    mysql)
+		if ! DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "$db_name" "SELECT NULL" 2>/dev/null; then
+			if ! DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "" \
+			     "CREATE DATABASE $db_name"; then
+				echo "Failed to create database (incorrect admin username/password?)" >&2
+				echo "It's also possible that mysql-server wasn't running.  After install" >&2
+				echo "is completed, you will need to make sure mysql-server is running" >&2
+				echo "and that you supplied correct information. Try:" >&2
+				echo "sudo dpkg-reconfigure moodle" >&2
+				# silently exit, instead pop up a notification for user indicating this
+				unud=/var/lib/update-notifier/user.d
+				if test -d $uund; then
+				    cp -f /usr/share/moodle/moodle-reconfigure-required.update-notifier \
+				          /var/lib/update-notifier/user.d/moodle-reconfigure-required
+				fi
+				exit 0
+			fi
+		fi
+		DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "$db_name" \
+		    "GRANT ALL PRIVILEGES ON $db_name.* TO $dbu_name@localhost IDENTIFIED BY '$dbu_password'"
 
-	case $db_server in
-	    "postgresql")
-			. /usr/share/wwwconfig-common/pgsql-createuser.sh
-			if [ "$status" = "error" ]
-			then
-				err=1
-				echo $error
-			fi
-			. /usr/share/wwwconfig-common/pgsql-createdb.sh
-			if [ "$status" = "error" ]
-			then
-				err=1
-				echo $error
-			fi
-		;;
-
-	    "mysql-server")
-			. /usr/share/wwwconfig-common/mysql-createuser.sh
-			if [ "$status" = "error" ]
-			then
-				err=1
-				echo $error
-			fi
-			. /usr/share/wwwconfig-common/mysql-createdb.sh
-			if [ "$status" = "error" ]
-			then
-				err=1
-				echo $error
-			fi
-		;;
+		DoMySQL "$db_server" "$db_host" "$dba_name" "$dba_password" "$db_name" \
+		    "GRANT ALL PRIVILEGES ON $db_name.* TO $dbu_name@'%' IDENTIFIED BY '$dbu_password'"
+	    ;;
+	    postgres7)
+	        if [ "$db_pgcreate" = "false" ] || ! check_pgsafe "$db_name"; then
+		    echo "You must create your PostgreSQL database manually."
+		else
+                    id "$dbu_name" 2> /dev/null || adduser --system --home /nonexistent --no-create-home --disabled-login "$dbu_name"
+		    su -c "psql --command \"CREATE ROLE $dbu_name PASSWORD '$dbu_password' NOSUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;\"" postgres
+		    su -c "createdb -E UTF8 -O \"$dbu_name\" \"$db_name\"" postgres
+		fi
+	    ;;
 	esac
-	if [ "$err" = "1" ]
-	then
-		echo "---------------------------------------------------------"
-		echo "I've tried my best to create the moodle user and database"
-		echo "but an error has occurred"
-		echo "---------------------------------------------------------"
-		echo "You will have to set up the moodle user and database yourself"
-		echo "---------------------------------------------------------"
-	fi
-
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
