New apache config file - for virtual host. Added check for php5-(pg|my)sql being installed.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -27,6 +27,16 @@ fi
 # source dbconfig-common stuff
 . /usr/share/dbconfig-common/dpkg/postinst
 
+check_php5mysql_notinstalled() {
+    dpkg -s php5-mysql | grep Status | grep -q installed >/dev/null 2>&1 && return 0
+    return 1
+}
+
+check_php5psql_notinstalled() {
+    dpkg -s php5-pgsql | grep Status | grep -q installed >/dev/null 2>&1 && return 0
+    return 1
+}
+
 moodle_config() {
 	local cfile=/etc/moodle/config.php
 	local tempfile=`tempfile`
@@ -100,22 +110,18 @@ apache_config() {
 	tmp=`echo $wwwroot | sed 's#^https*://[^/]*/*##'`
 
 	if [ -n "$tmp" ]; then
-		tmp_alias=<<EOS
-#Uncomment the line below if you want to use alias
+		tmp_alias=`echo "#Uncomment the line below if you want to use alias
 #This will not work well with virtual hosts
-#Alias /${tmp} /usr/share/moodle/
-EOS
+#Alias /${tmp} /usr/share/moodle/"`
 	else
-	tmp_alias=<<EOS
-#You can't use alias becuse you Moodls is not in a sub-directory
-#Create appropriate virtual host insted.
-EOS
+		tmp_alias=`echo "#You can't use alias becuse you Moodls is not in a sub-directory
+#Create appropriate virtual host insted."`
 	fi
 
 	cat > $tempfile <<EOF
-# This file has been generated by debconf
+# This file has been generated by debconf 
 
-${alias}
+${tmp_alias}
 
 <DirectoryMatch /usr/share/moodle/>
 
@@ -150,6 +156,38 @@ EOF
     ucf --debconf-ok $tempfile $cfile
     chmod 640 $cfile
     chown www-data:www-data $cfile
+
+
+#Sample config for the virtual host
+	tempfile=`tempfile`
+        cfile="/etc/moodle/apache.vhost.conf"
+	server=`echo $wwwroot |cut -d'/' -f3`
+	cat > $tempfile <<EOF
+<VirtualHost *:80>
+        ServerAdmin webmaster@${server}
+	ServerName ${server}
+        DocumentRoot /usr/share/moodle/
+        <Directory /usr/share/moodle/>
+                Options Indexes FollowSymLinks MultiViews
+                AllowOverride All
+                Order allow,deny
+                allow from all
+        </Directory>
+
+        ErrorLog \${APACHE_LOG_DIR}/error.log
+
+        # Possible values include: debug, info, notice, warn, error, crit,
+        # alert, emerg.
+        LogLevel warn
+
+        CustomLog \${APACHE_LOG_DIR}/access.log combined
+</VirtualHost>
+EOF
+
+    ucf --debconf-ok $tempfile $cfile
+    chmod 640 $cfile
+    chown www-data:www-data $cfile
+
 }
 
 dbc_first_version="1.9.8-1"
@@ -186,6 +224,17 @@ case "$1" in
 
         [ ! -h /usr/share/moodle/lib/magpie ] && ln -s /usr/share/php/magpierss /usr/share/moodle/lib/magpie
 
+	if [ "$dbc_dbtype" = "mysql" -a check_php5mysql_notinstalled ]; then
+		echo 'Error - You have specified that you wish to use a mysql' >&2
+	        echo 'database, but php5-mysql is not installed. You must install' >&2
+		echo 'php5-mysql before you can complete your moodle installation.' >&2
+	fi
+
+	if [ "$dbc_dbtype" = "postgresql" -a check_php5psql_notinstalled ]; then
+		echo 'Error - You have specified that you wish to use a postgresql' >&2
+		echo 'database, but php5-pgsql is not installed. You must install' >&2
+		echo 'php5-pgsql before you can complete your moodle installation.' >&2
+	fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
